#!/usr/bin/env bash
#
# program
# -------
# program that runs fitmodel.py 
# usage: ./program CELL_NUM INIT_NUM_LNK INIT_NUM_S
#
# (C) bongsoos 2015
#
# fitmodel
# --------
# run using python3, module fitmodel.py
#
# usage: ./fitmodel.py $cell_num $model $objective $pathway $init_num_LNK $init_num_S $num_optims $crossval $is_grad
# ex) $ ./fitmodel.py g9 LNK LNK 2 g9 g9 2 True False & 
#
# Options(env variables)
# -------
#    cell_num
#    model
#    objective
#    pathway 
#    init_num_LNK
#    init_num_S
#    num_optims
#    crossval
#    is_grad
#
# cell_num
# --------
# g4 g6 g8 g9 g9apb g11 g12 g13 g15 g17 g17apb g19 g19apb g20 g20apb
#

model=Spiking
objective=Spiking
num_optims=1
pathway=1
crossval=True
is_grad=True
bnd_mode=0
gamma=0.5

function start_fit {
    # start_fit 
    # usage: start_fit CELL_NUM INIT_NUM_LNK INIT_NUM_S

    if [ "$model" = "Spiking" ] || [ "$model" = "Spiking_est" ];then
        # echo "$model is Spiking"
        # Save output using the $init_num_S variable
        nohup ./fitmodel.py  $1 $model $objective $pathway $2 $3 $num_optims $crossval $is_grad $bnd_mode $gamma > $1.$3.out
    elif [ "$model" = "LNKS" ] || [ "$model" = "LNKS_MP" ] || [ "$model" = "LNKS_spike" ];then
        # echo "$model is Spiking"
        # Save output using the $init_num_S variable
        nohup ./fitmodel.py  $1 $model $objective $pathway $2 $3 $num_optims $crossval $is_grad $bnd_mode $gamma > $1.$2.$3.out
    else
        # echo "$model is LNKS"
        # Save output using the $init_num_LNK variable
        nohup ./fitmodel.py  $1 $model $objective $pathway $2 $3 $num_optims $crossval $is_grad $bnd_mode $gamma > $1.$2.out
    fi

}

hostname
#echo $1 $2 $3
start_fit $1 $2 $3

