#!/usr/bin/env bash
#
# simple-run 
# -------
# simple program that runs one fitmodel.py 
# usage: ./simple-run
#
# (C) bongsoos 2015
#
# fitmodel
# --------
# run using python3, module fitmodel.py
#
# usage: ./fitmodel.py $cell_num $model $objective $pathway $init_num_LNK $init_num_S $num_optims $crossval $is_grad
# ex) $ ./fitmodel.py g9 LNK LNK 2 g9 g9 2 True False & 
#
# Options(env variables)
# -------
#    cell_num
#    model
#    objective
#    pathway 
#    init_num_LNK
#    init_num_S
#    num_optims
#    crossval
#    is_grad
#
# cell_num
# --------
# g4 g6 g8 g9 g9apb g11 g12 g13 g15 g17 g17apb g19 g19apb g20 g20apb
#

cell_num=g9apb
init_num_LNK=g11
init_num_S=g20
model=LNKS
objective=LNKS
num_optims=1
pathway=1
crossval=True
is_grad=True

function start_fit {
    # start_fit 
    # usage: start_fit cell_num init_num_lnk init_num_s

    if [ "$model" = "Spiking" ] || [ "$model" = "Spiking_est" ];then
        # echo "$model is Spiking"
        # Save output using the $init_num_S variable
        nohup ./fitmodel.py  $1 $model $objective $pathway $2 $3 $num_optims $crossval $is_grad > $1.$3.out
    elif [ "$model" = "LNKS" ] || [ "$model" = "LNKS_MP" ];then
        # echo "$model is Spiking"
        # Save output using the $init_num_S variable
        nohup ./fitmodel.py  $1 $model $objective $pathway $2 $3 $num_optims $crossval $is_grad > $1.$2.$3.out
    else
        # echo "$model is LNKS"
        # Save output using the $init_num_LNK variable
        nohup ./fitmodel.py  $1 $model $objective $pathway $2 $3 $num_optims $crossval $is_grad > $1.$2.out
    fi

}

hostname
#echo $1 $2 $3
start_fit $cell_num $init_num_LNK $init_num_S

